### ISSUE TITLE
nlcd file error

### ISSUE THREAD

**Issue by haris021** [USGS-VIZLAB/chart-challenge-22#50]
I have been trying to run the code however i keep getting this error, i have tried to delete and rerun it stills keeps on returning the same error.
nlcd file E:\scripts\chart-challenge-22-main\23_tiles_msleckman\RAW\NLCD\NLCD2001_LC_N36W072.zip corrupt or incomplete. Please delete the file and try again

Shall be highly obliged if you could look into this

**Comment by cnell-usgs** [comment]
I think this is related to an issue with the `FedData` package (https://github.com/ropensci/FedData/issues/62) . If you install the development version of the package it should fix this error. 
```#install.packages("devtools")
devtools::install_github("ropensci/FedData")
```

**Comment by haris021** [comment]
Thank you for your response. It worked.
However now getting this error : "cannot allocate vector of size 333.2 Mb"

**Comment by cnell-usgs** [comment]
This means that your device does not have the memory to complete the build. What stage are you getting this error message at?

**Comment by haris021** [comment]
Thank you for your response. It was indeed the issue of the capacity of my machine. However, i used my limited dataset to plot the similar figure. Thanks again
